# Generated by Django 5.2.17 on 2026-09-13 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_avatar_studentprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('score_statistical', models.FloatField(default=0)),
                ('score_technical', models.FloatField(default=0)),
                ('score_digital_governance', models.FloatField(default=0)),
                ('score_behavioural', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('quiz_payload', models.JSONField(default=dict, help_text='AI-generated questions')),
                ('answers_payload', models.JSONField(default=dict, help_text="User's submitted answers")),
                ('ai_feedback', models.JSONField(default=dict, help_text='AI evaluation of descriptive answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic Attempt',
                'verbose_name_plural': 'Diagnostic Attempts',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
