# Generated by Django 5.2.17 on 2026-09-14 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_diagnosticattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
